/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef SC_TRACING_H_
#define SC_TRACING_H_

namespace sc
{
namespace trace
{

template<typename T>
class TraceObserver
{
public:

    virtual ~TraceObserver()
    {
    }

    virtual void stateEntered( T state ) = 0;

    virtual void stateExited( T state ) = 0;

};
} /* namespace sc::trace */
} /* namespace sc */

#endif /* SC_TRACING */

