ETH008_IP="192.168.5.11"

RASPI_IP="192.168.5.12"
RASPI_PASSWORD="pi"
RASPI_USER="pi"

GRINDER_DESCRIPTION[1]="Grinder Neuer MOSFET"
GRINDER_GPIO_MOTOR_ON[1]=
GRINDER_TEMP_CH_MOSFET[1]=1
GRINDER_TEMP_CH_HOUSING[1]=2
GRINDER_MONITOR_ESP[1]=n
GRINDER_MONITOR_DEV[1]=/dev/ttyUSB0

GRINDER_DESCRIPTION[2]="HeyCafe Grinder #2"
GRINDER_GPIO_MOTOR_ON[2]=25
GRINDER_TEMP_CH_MOSFET[2]=3
GRINDER_TEMP_CH_HOUSING[2]=4
GRINDER_MONITOR_ESP[2]=y
GRINDER_MONITOR_DEV[2]=/dev/ttyUSB0

GRINDER_DESCRIPTION[3]="HeyCafe Grinder ???"
GRINDER_GPIO_MOTOR_ON[3]=
GRINDER_TEMP_CH_MOSFET[3]=5
GRINDER_TEMP_CH_HOUSING[3]=6
GRINDER_MONITOR_ESP[3]=n
GRINDER_MONITOR_DEV[3]=/dev/ttyUSB0

